# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Musing on random technical subjects
email: acepace@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Random writing of a geek, sometimes security and OS, sometimes just junk.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.acepace.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ace__pace
github_username:  acepace
author: Ace Pace
navbar-links:
  About Me: "about"
avatar: "/assets/img/excellent.jpg"
social-network-links:
  email: "acepace@gmail.com"
  github: acepace
  twitter: ace__pace
  rss: true
  stackoverflow: "40115/daniel-goldberg"
share-links-active:
  twitter: true
  linkedin: true
url-pretty: "www.acepace.net"
link-tags: true
excerpt_length: 50

timezone: "Asia/Jerusalem"
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
kramdown:
  input: GFM

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

google_analytics: UA-138660704-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
